name: Test container workflow

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  run-main-build:
    name: Build uBlue-OS Main
    continue-on-error: false
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      fail-fast: false
      max-parallel: 5
      matrix:
        image_name:
          - silverblue
          - kinoite
          - sericea
          - onyx
          - base
          - lxqt
          - lazurite
          - mate
          - vauxite
        major_version:
          - 39
        image_variant: 
          - nokmods
        include:
          - major_version: 39
            support: latest
          #- major_version: 38
          #  support: gts
        exclude:
          # There is no Fedora 39 version of lxqt as it was replaced by lazurite
          - image_name: lxqt
            major_version: 39
    steps:
      - name: Build image
        uses: JasonN3/build-action@action
        with:
          image_name: ${{ matrix.image_name }}
          image_variant: ${{ matrix.image_variant }}
          version: ${{ matrix.major_version }}
          support: ${{ matrix.support }}
          signing_key: ${{ secrets.SIGNING_SECRET }}
          target: ${{ matrix.image_variant }}
          container_registry: ghcr.io/${{ github.repository }}
          container_repo: ublue-os/main
          container_ref: main

      - name: Delete main packages
        if: matrix.image_variant == 'main'
        uses: actions/delete-package-versions@v4
        with: 
          package-name: ${{ github.event.repository.name }}/${{ matrix.image_name }}
          package-type: 'container'
          min-versions-to-keep: 0
          delete-only-untagged-versions: 'false'

      - name: Delete variant packages
        if: matrix.image_variant != 'main'
        uses: actions/delete-package-versions@v4
        with: 
          package-name: ${{ github.event.repository.name }}/${{ matrix.image_name }}-${{ matrix.image_variant }}
          package-type: 'container'
          min-versions-to-keep: 0
          delete-only-untagged-versions: 'false'

  run-bluefin-build:
    name: Build uBlue-OS Bluefin
    continue-on-error: false
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      fail-fast: false
      max-parallel: 5
      matrix:
        image_name:
          - bluefin
          - bluefin-dx
        major_version:
          - 39
        image_variant:
          - main
          - nvidia
          - asus
          - asus-nvidia
          - framework
          - surface
          - surface-nvidia
        include:
          - major_version: 39
            support: latest
          #- major_version: 38
          #  support: gts
        exclude:
          # There is no Fedora 39 version of lxqt as it was replaced by lazurite
          - image_name: lxqt
            major_version: 39
    steps:
      - name: Determine AKMODS_FLAVOR
        run: |
          if [[ "${{ matrix.image_flavor }}" =~ "asus" ]]; then
              echo "AKMODS_FLAVOR=asus" >> $GITHUB_ENV
          elif [[ "${{ matrix.image_flavor }}" =~ "surface" ]]; then
              echo "AKMODS_FLAVOR=surface" >> $GITHUB_ENV
          else
              echo "AKMODS_FLAVOR=main" >> $GITHUB_ENV
          fi

      - name: Build image
        uses: JasonN3/build-action@action
        with:
          image_name: ${{ matrix.image_name }}
          image_variant: ${{ matrix.image_variant }}
          version: ${{ matrix.major_version }}
          support: ${{ matrix.support }}
          signing_key: ${{ secrets.SIGNING_SECRET }}
          target: ${{ matrix.image_name }}
          extra_build_args: |
            AKMODS_FLAVOR=${{ env.AKMODS_FLAVOR }}
          container_registry: ghcr.io/${{ github.repository }}
          container_repo: ublue-os/bluefin
          container_ref: main
      
      - name: Delete main packages
        if: matrix.image_variant == 'main'
        uses: actions/delete-package-versions@v4
        with: 
          package-name: ${{ github.event.repository.name }}/${{ matrix.image_name }}
          package-type: 'container'
          min-versions-to-keep: 0
          delete-only-untagged-versions: 'false'

      - name: Delete variant packages
        if: matrix.image_variant != 'main'
        uses: actions/delete-package-versions@v4
        with: 
          package-name: ${{ github.event.repository.name }}/${{ matrix.image_name }}-${{ matrix.image_variant }}
          package-type: 'container'
          min-versions-to-keep: 0
          delete-only-untagged-versions: 'false'